#-----------------------------
# Docker イメージのベースイメージ
#-----------------------------
FROM tensorflow/tensorflow:1.4.0-gpu-py3

#-----------------------------
# 基本ライブラリのインストール
#-----------------------------
# インストール時のキー入力待ちをなくす環境変数
ENV DEBIAN_FRONTEND noninteractive

RUN set -x && apt-get update && apt-get install -y --no-install-recommends \
    sudo \
    git \
    curl \
    wget \
    bzip2 \
    ca-certificates \
    python3-pip \
    libx11-6 \
    libgl1-mesa-dev \
    python3-tk \
    # imageのサイズを小さくするためにキャッシュ削除
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

RUN pip install --upgrade pip

#-----------------------------
# 環境変数
#-----------------------------
ENV LC_ALL=C.UTF-8
ENV export LANG=C.UTF-8
ENV PYTHONIOENCODING utf-8

#-----------------------------
# 追加ライブラリのインストール
#-----------------------------
RUN pip install pillow==6.2.1
RUN pip install opencv-python
RUN pip install matplotlib
RUN pip install imageio
RUN pip install tqdm
RUN pip install scikit-learn
